---

- import_tasks: extroot.yml
  when:
    - openwrt_extroot
    - not openwrt_ansible_bootstrap
  tags:
    - openwrt_extroot
    - overlay
    - pivot-overlay

- import_tasks: bootstrap.yml
  when:
    - not openwrt_extroot
    - openwrt_ansible_bootstrap
  tags:
    - openwrt_ansible_bootstrap
    - python

# - import_tasks: packages.yml
#   when:
#     - not openwrt_extroot
#     - packages
#   tags:
#     - openwrt_ansible_bootstrap
#     - python

- import_tasks: dhcp.yml
  tags: dhcp

- import_tasks: system.yml
  tags: system

# dropbear.@dropbear[0]
- name: dropbear configuration
  uci:
    command: "batch"
    value: "{{openwrt_dropbear}}"
  notify:
    - reload dropbear

# - name: apply ddns uci settings
#   uci: command=set key="ddns.myddns.{{ item.key }}" value="{{ item.value }}"
#   with_dict: "{{ddns}}'
#   notify:
#     - uci commit
#     - restart ddns

# - name: apply wireless uci settings
#   uci: command=set key="wireless.@wifi-iface[{{ item.1 }}].{{ item.0.key }}" value="{{ item.0.value }}"
#   with_subelements:
#     - wireless
#     - ifaces
#   notify:
#     - uci commit
#     - reload network

# - import_tasks: firewall.yml
#   tags: firewall
