---

######################
# Action to perform.
######################

# Create an extroot by running script `files/extroot.sh`.
openwrt_extroot: False

# Ansible bootstrap. Install Ansible dependencies using the raw module.
openwrt_ansible_bootstrap: False

# Install packages by running script 'files/packages.sh'
openwrt_packages: False

# dhcp subsystem
openwrt_dhcp:
  dnsmasq: |
    # Don't forward DNS-Requests without DNS-Name
    set dhcp.@dnsmasq[0].domainneeded='1'
    set dhcp.@dnsmasq[0].boguspriv='1'
    set dhcp.@dnsmasq[0].localise_queries='1'
    # Discard upstream RFC1918 responses
    set dhcp.@dnsmasq[0].rebind_protection='1'
    # Allow upstream responses in the 127.0.0.0/8 range, e.g. for RBL services
    set dhcp.@dnsmasq[0].rebind_localhost='1'
    # Local domain specification. Names matching this domain are never forwarded
    # and are resolved from DHCP or hosts files only.
    set dhcp.@dnsmasq[0].local='/lan/'
    # Local domain suffix appended to DHCP names and hosts file entries
    set dhcp.@dnsmasq[0].domain='lan'
    # Add the domain to simple names (without a period) in /etc/hosts in the
    # same way as for DHCP-derived names. Note that this does not apply to
    # domain names in cnames, PTR records, TXT records etc.
    set dhcp.@dnsmasq[0].expandhosts='1'
    # This is the only DHCP in the local network
    set dhcp.@dnsmasq[0].authoritative='1'
    # Read /etc/ethers for information about hosts for the DHCP server.
    set dhcp.@dnsmasq[0].readethers='1'
    # List of DNS servers to forward requests to
    # set dhcp.@dnsmasq[0].server=''
    # Limit DNS service to subnets interfaces on which we are serving DNS.
    set dhcp.@dnsmasq[0].localservice='0'
    #  Bind only to specific interfaces rather than wildcard address.
    set dhcp.@dnsmasq[0].nonwildcard='1'

  # DNS entries. This works well with updating existing entries only.
  domains: null
   # set dhcp.@domain[0]=domain
   # set dhcp.@domain[0].name=example.org
   # set dhcp.@domain[0].ip=192.168.2.145

  # mac reservation
  # The format of /etc/ethers is a hardware address, followed by either a
  # hostname or an address. Better use that instead.
  hosts: |
    set dhcp.@host[0]=host
    set dhcp.@host[0].mac=78:24:af:38:9b:df
    set dhcp.@host[0].ip=192.168.2.205
    set dhcp.@host[0].name=ds00.lan

  interfaces:
    - lan: |
        set dhcp.lan=dhcp
        set dhcp.lan.interface='lan'
        set dhcp.lan.start='100'
        set dhcp.lan.limit='150'
        set dhcp.lan.leasetime='12h'
        set dhcp.lan.dhcpv6='server'
        set dhcp.lan.ra='server'
        set dhcp.lan.ra_management='2'

    # - wan: |
    #     set dhcp.wan=dhcp
    #     set dhcp.wan.interface='wan'
    #     set dhcp.wan.ignore='1'
    #     set dhcp.odhcpd=odhcpd
    #     set dhcp.odhcpd.maindhcp='0'

# dropbear
openwrt_dropbear: |
  # lan
  set dropbear.@dropbear[0].PasswordAuth='on'
  set dropbear.@dropbear[0].Port='22222'
  # Allow remote hosts to connect to local SSH forwarded ports
  set dropbear.@dropbear[0].GatewayPorts='on'
  # set this to prevent binding to wildcard adress
  set dropbear.@dropbear[0].Interface='lan'

# System
openwrt_system:
  hostname: gw00
  # see https://lede-project.org/docs/user-guide/system_configuration
  timezone: |
    set system.@system[0].zonename='utc'
    set system.@system[0].timezone='GMT0'
  ntp: |
    set system.ntp.enabled='1'
    set system.ntp.enable_server='1'
    set system.ntp.server='resolver1.level3.net' 'alpha.codatory.net' 'ntp1.torix.ca' 'ntp3.torix.ca'

# firewall:
#   # zone 0 is wan
#   # zone 1 is lan
#   # zone 2 is guest
#   policies:
#     - chain: output
#       policy: ACCEPT
#       zone: [0,1,2]

#     - chain: input
#       policy: ACCEPT
#       zone: [1]
#     - chain: input
#       policy: REJECT
#       zone: [0,2]

#     - chain: forward
#       policy: ACCEPT
#       zone: [1]
#     - chain: forward
#       policy: REJECT
#       zone: [0,2]

#   forwarding:
#     - index: 0
#       settings:
#       - key: src
#         value: guest
#       - key: dest
#         value: wan

#   redirect: []

# # lede_pkgs:
# #   - vim
# #   - tmux
# #   - git
# #   - tcpdump
# #   - nmap
# #   - mtr
# #   - rsync
# #   - zsh
# #   - shadow
# #   - sudo
# #   - bind-dig
# #   - python3
# #   - python3-pip
# #   - block-mount
# #   - kmod-usb-storage
# #   - kmod-fs-ext4
# #   - wget
# #   - curl
# #   - less
# #   - zsh
# #   - wol
# #   - etherwake
# #   # - ca-certificates
# #   # - openssh-client
# #   # - openssh-server
# #   # - openssh-keygen
# #   # - openssh-sftp-server
# #   # - openssh-client-utils
# #   # - python3-openssl
