---

# Reload the appropriate subsystem.
# Available subsystems are:
#     dnsmasq, dropbear, firewall, fstab, network, qos, samba, system, wireless

- name: reload dnsmasq
  raw: /etc/init.d/dnsmasq reload

- name: reload system
  raw: /etc/init.d/system reload

- name: reload sysntpd
  raw: /etc/init.d/sysntpd reload

- name: reload dropbear
  raw: /etc/init.d/dropbear reload

- name: reload firewall
  raw: /etc/init.d/firewall reload

- name: reload network
  raw: /etc/init.d/network reload

# - name: restart snmpd
#   raw: /etc/init.d/snmpd restart

- name: restart ddns
  raw: /etc/init.d/ddns restart
